services:
  user-service:
    image: docker.io/library/mysql:8.0
    restart: always
    env_file:
      - .env 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # S3 API port
      - "9001:9001"     # Web UI port
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped
  
  # redis:
  #   image: docker.io/library/redis:7.2
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: always

volumes:
  # redis_data:
  minio-data:
